extends:
  - react-app
  - react-app/jest

parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json

rules:
  semi: [warn, never]
  quotes: [warn, single]
  max-len:
    [
      warn,
      100,
      2,
      {
        ignoreUrls: true,
        ignoreComments: false,
        ignoreRegExpLiterals: true,
        ignoreTemplateLiterals: true,
        ignoreStrings: true,
      },
    ]
  indent: [warn, 2, { SwitchCase: 1, flatTernaryExpressions: true }]
  no-trailing-spaces: warn
  no-multi-spaces: warn
  arrow-spacing: warn
  '@typescript-eslint/type-annotation-spacing': warn
  object-curly-spacing: off
  '@typescript-eslint/object-curly-spacing': [warn, always]
  func-call-spacing: off
  '@typescript-eslint/func-call-spacing': warn
  comma-spacing: off
  '@typescript-eslint/comma-spacing': warn
  comma-dangle: [warn, always-multiline]
  '@typescript-eslint/naming-convention':
    [warn, { selector: enum, format: [PascalCase] }, { selector: enumMember, format: [UPPER_CASE] }]
  '@typescript-eslint/space-infix-ops': [warn]
  '@typescript-eslint/keyword-spacing': warn
  key-spacing: warn
  block-spacing: warn

  # Bad ideas / code smells
  no-param-reassign: error
  no-eval: error
  no-extend-native: error
  no-duplicate-imports: error
  no-new-wrappers: error
  no-underscore-dangle: error
  no-var: error
  no-unreachable: error
  no-fallthrough: error
  one-var: [error, never]
  no-whitespace-before-property: error
